import { useLang } from "@/contexts/LangContext";
import { LOGO } from "@/lib/icons";
import { Link } from "wouter";
import LangSwitcher from "@/components/LangSwitcher";

export default function EULA() {
  const { t, lang } = useLang();
  const isRTL = t.dir === "rtl";
  const fontClass = lang === "ar" ? "font-arabic" : lang === "he" ? "font-hebrew" : "font-display";

  return (
    <div
      className={`min-h-screen bg-[#0a0612] text-[#e8dcc8] ${fontClass}`}
      style={{ fontFamily: t.fontBody }}
      dir={t.dir}
    >
      {/* Nav */}
      <nav className="fixed top-0 inset-x-0 z-50 bg-[#0a0612]/80 backdrop-blur-md border-b border-[#d4a574]/10">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/">
            <img src={LOGO.icon} alt="MAKTUBA" className="h-8 w-auto cursor-pointer" />
          </Link>
          <LangSwitcher />
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 pt-28 pb-20">
        <h1 className="font-display text-3xl sm:text-4xl text-[#d4a574] mb-8 tracking-wider">
          End User License Agreement
        </h1>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-[#e8dcc8]/70 leading-relaxed">
          <p><strong>Effective Date:</strong> April 2026</p>
          <p><strong>App Name:</strong> MAKTUBA — What Is Written</p>
          <p><strong>Developer:</strong> KBR Global LTD</p>

          <h2 className="text-[#d4a574] text-xl mt-8">1. Acceptance of Terms</h2>
          <p>By downloading, installing, or using the MAKTUBA application ("App"), you agree to be bound by this End User License Agreement ("EULA"). If you do not agree to these terms, do not use the App.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">2. License Grant</h2>
          <p>We grant you a limited, non-exclusive, non-transferable, revocable license to use the App for personal, non-commercial purposes on devices you own or control, subject to this EULA.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">3. Entertainment Purpose</h2>
          <p>The App provides AI-generated mystical readings, horoscopes, and spiritual content for entertainment purposes only. The content should not be used as a substitute for professional advice (medical, legal, financial, psychological, or otherwise). We make no claims about the accuracy, reliability, or predictive value of any reading or content generated by the App.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">4. In-App Purchases</h2>
          <p>The App uses a virtual currency system called "Keys" (מפתחות). Keys can be purchased through in-app purchases as one-time packs or granted through subscription plans, and are used to unlock premium readings. Keys are granted all at once at time of purchase, do not expire, and remain available to the user even after a subscription period ends. All purchases are final and non-refundable, except as required by applicable law or the policies of the platform (Apple App Store, Google Play Store) through which you made the purchase.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">5. Subscription Terms</h2>
          <p>Premium subscriptions grant a bundled quantity of Keys at the start of each billing period, along with access to all readings. Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current period. You can manage or cancel your subscription through your device's app store settings.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">6. User Content</h2>
          <p>You may submit personal information (birth date, zodiac sign, questions) to receive personalized readings. You retain ownership of your content. By submitting content, you grant us a limited license to process it for the purpose of generating your readings.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">7. Intellectual Property</h2>
          <p>All content, artwork, character designs (including the Maktuba character), tarot card designs, and other creative assets in the App are the exclusive property of KBR Global LTD. You may not copy, modify, distribute, or create derivative works from any App content.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">8. Privacy</h2>
          <p>Your use of the App is also governed by our <Link href="/privacy" className="text-[#d4a574] underline">Privacy Policy</Link>. By using the App, you consent to the collection and use of your information as described therein.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">9. Termination</h2>
          <p>We may terminate or suspend your access to the App at any time, without prior notice, for conduct that we believe violates this EULA or is harmful to other users, us, or third parties.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">10. Disclaimer of Warranties</h2>
          <p>THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">11. Limitation of Liability</h2>
          <p>IN NO EVENT SHALL KBR GLOBAL LTD BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE APP.</p>

          <h2 className="text-[#d4a574] text-xl mt-8">12. Contact</h2>
          <p>For questions about this EULA, contact us at: <a href="mailto:support@maktuba.app" className="text-[#d4a574] underline">support@maktuba.app</a></p>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-[#d4a574]/10 py-8 text-center text-sm text-[#e8dcc8]/30">
        <p>&copy; 2026 KBR Global LTD. All rights reserved.</p>
      </footer>
    </div>
  );
}
